### ISSUE TITLE
Issue using anaconda

### ISSUE THREAD

**Issue by sanathsk009** [poldracklab/lmod_modules#2]
Hi Podrack lab,

We have been using anaconda on Sherlock using this module, however recently we encountered the following error. 

We are able to load the anaconda module, however simple conda commands like "conda --version" do not seem to work due to a missing directory issue. Any advise towards fixing this would be appreciated! Thanks!

<img width="1680" alt="conda-issue" src="https://user-images.githubusercontent.com/47834969/153657408-7cbaaab8-7521-4f78-a4cb-2dcdbf2e0736.png">

P.S.: I am a PhD student at Stanford in Susan Athey's lab.

**Comment by effigies** [comment]
Hi @sanathsk009, I would recommend not using the anaconda module and instead [installing miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) in your own home directory.

I don't know why the lab module isn't still working, but it is quite old at this point. We don't use it anymore, preferring miniconda environments, so it's more likely to get removed than fixed.

**Comment by sanathsk009** [comment]
Got it, thanks for the advise!
